stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    - data_ingestion.random_state
    - data_ingestion.frac
    outs:
    - data/external
  
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - data/external
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - src/features/feature_engineering.py
    - data/interim
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
    - models/vectorizer.pkl

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - src/models/model_building.py
    - data/processed
    params:
    - model_building.n_estimators
    - model_building.min_samples_split
    outs:
    - models/model.pkl

